services:
  - type: web
    name: debugpilot
    runtime: python
    buildCommand: apt-get install -y gcc g++ default-jdk-headless php ruby-full && pip install -r requirements.txt && npm install -g ts-node typescript
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GROQ_API_KEY
        sync: false